services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app                  # live reload
      - /app/node_modules       # preserve container node_modules
      - uploads:/app/uploads
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/realtime-chat
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-dev-secret-change-in-prod}
      - UPLOAD_DIR=./uploads
      - MAX_FILE_SIZE=10485760
      - VAPID_PUBLIC_KEY=BBoYqPPBAhv0if9G5dGIaIRldOrD2x5KJhbebJsxGVA40n2Hkw94T6SqBEQk-CQg9Q9iUBrdt2gO4L66WmyvbK4      
      - VAPID_PRIVATE_KEY=uXPxk3YF662VoS_YadliCzHrNEGV-H3PXgLdINYEyjQ
      - VAPID_SUBJECT=mailto:admin@example.com
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:
  uploads:
